#!/bin/sh

USB_DEV_PATH=/dev/usb

start_dextension()
{
   TTY=" "

# check if a dextension dongle is already connected   
   if [ -f /var/run/dextension ]; 
   then
          echo "already a dextension device connected!"
          exit 1
   else
         touch /var/run/dextension
   fi;
   
   for PARAM in $USB_DEV_PATH/ttyUSB0 $USB_DEV_PATH/ttyUSB1 $USB_DEV_PATH/ttyUSB2 $USB_DEV_PATH/ttyUSB3 
   do
      stty -F $PARAM > /dev/null
      
      if [ $? != 0 ];
      then
         continue;
      else
         echo DECT_DONGLE_TTY=$PARAM > /var/run/dextension
         TTY=$PARAM
         break; 
      fi;
      
   done;
   
   if [ $TTY = " " ];
   then
      echo "no dextension device found!"
      rm -f /var/run/dextension
   else
      echo "add dextension device"
      echo $TTY
      /etc/init.d/mdg_usb start $TTY
      /etc/init.d/osis_services start
   fi;
   
}

stop_dextension()
{
   echo "remove dextension device"
   /etc/init.d/mdg_usb stop
   rm -f /var/run/dextension
   /etc/init.d/osis_services stop
}

case $ACTION in
   add)
      start_dextension
      ;;
      
   remove)
      stop_dextension
      ;;
esac;	

