#!/bin/sh

ID_FILE='/var/run/chckd_atom'
BIN_FILE='/usr/bin/checkd'

case $1 in
    start)
	# start checkd
	if [ -f "$BIN_FILE" ] ; then
		/bin/echo "checkd start ..."
		/usr/bin/checkd -d
	fi
	;;
    stop)
	# stop checkd
	if [ -f "$BIN_FILE" ] ; then
		/bin/echo "checkd stop ..."
		if [ -f "$ID_FILE" ] ; then
			CHECKD_ID=$(cat ${ID_FILE})
			/bin/echo ${CHECKD_ID}
			kill ${CHECKD_ID}
			rm -f ${ID_FILE}
		fi
	fi
	;;
    *)
	
esac



