#!/bin/sh

# This is the init script for the Entropic clinkd daemon.

CLINKD=/usr/bin/clinkd
CLINKD_NAME=clinkd
KERNEL_MODULE=/lib/modules/2.6.30/kernel/net/entropic/CandDdvr.ko
KERNEL_MODULE_NAME=CandDdvr
SOCKNAME=/tmp/clink.sock./dev
CLINKCONF_DEST=/rw/etc/
CLINKCONF_NAME=clink.conf


case $1 in
  start)

    #CPE_P00075123:CJ:Change clink.conf to a rw location
    if ! [ -e $CLINKCONF_DEST$CLINKCONF_NAME ] ; then
        echo "${CLINKCONF_DEST}${CLINKCONF_NAME} does not exist. Copying the default file from archive"
        cp `find /archive/ . -name ${CLINKCONF_NAME}` $CLINKCONF_DEST 
        chmod 666 $CLINKCONF_DEST$CLINKCONF_NAME
    fi
    
    #CPE_P0007500:CJ: create temp file here instead of at the bottom where $CLINKD is started 
    #the file will be deleted when SoC has successfully booted
    echo "this file will be deleted automatically when the SoC is operational" > /tmp/EntropicBooting.txt

    # Make sockname
    echo "Entropic: Making ${SOCKNAME}..."
    mkdir -p $SOCKNAME

    # Load the kernel module if necessary
    if ! lsmod | grep -q "^${KERNEL_MODULE_NAME} " ; then
      # Not already loaded; try to load it.
      if ! [ -e $KERNEL_MODULE ] ; then
        echo "Entropic: $KERNEL_MODULE does not exist!  Exiting."
        exit 1
      fi

      echo "Entropic: loading ${KERNEL_MODULE}..."
      insmod $KERNEL_MODULE
    fi

    # Start clinkd
    if ! [ -e $CLINKD ] ; then
      echo "Entropic: $CLINKD does not exist!  Exiting."
      exit 2
    fi

    # CPE_P00083726: JHA: [CLI] Display log disturbed input command during automatic testing 
    # Toggle to ultra-quiet mode in CandD so that these lines aren't printed out
    #   in the serial port console:
    #   DIAG - Read PHY(11) REG(1a) (4091)
    #   DIAG - Write PHY(11) REG(1a) (40b1)
    echo "Entropic: Switching CandD to ultra-quiet mode."
    echo Q > /dev/CandD

    echo "Entropic: $CLINKD starting..."

    # Don't need the --firmware switch because firmware is compiled in because
    #   COMPILED_IN_BINARY CODE is set to 1 in host/Clink/ClinkD/Inc/ClnkDefs.h.
    # Don't need the --microcode switch apparently for the same reason.
    #  --microcode /etc/entripic/*phy.bin
    # Don't need the --mac-addr switch; it gives an 'unrecognized option' error.
    #  --mac-addr 00:1a:1b:1c:1d:1e

    # CPE_P00083726: JHA: [CLI] Display log disturbed input command during automatic testing 
    # Added two new levels of verbose; to display L_ERR only, use one v.
    # Removed the v's from the switches below.  Was -Dtvvf, now -Dtvf.
    $CLINKD -Dtvf /etc/clink.conf /dev/CandD &
    ;;

  stop)
    # CPE_P00086337: JHA: '/etc/init.d/clinkd stop' dumps core and reboots
    # Can't use 'killall clinkd' because it will also kill this script.
    # Get the pid of the clinkd process
    clinkd_pid=`ps | grep $CLINKD | grep -v grep | sed 's/^ *\([0-9]*\).*/\1/'`
    if [ "x_$clinkd_pid" != "x_" ] ; then
      kill $clinkd_pid
    else
      echo "Entropic: Cannot stop $CLINKD.  $CLINKD is not running."
    fi

    # Wait a while to make sure clinkd is dead, then flush the socket.  The
    #   socket can sometimes have cruft left in it from when the clinkd is
    #   killed.  That is only an issue if the clinkd is ever restarted, but
    #   it might as well be cleaned up here.
    sleep 5
    echo F > /dev/CandD

    # Don't rmmod the CandD_dvr driver.  It's not using any CPU anyway.
    ;;

  *)
    echo "Entropic: $CLINKD usage: $0 [start|stop]"
    exit 3
    ;;

esac
