#!/bin/sh

CTRL_PATH=/var/powermgr

case $1 in
    start)
	echo "Starting power manager..."
	touch ${CTRL_PATH}
	;;
    stop)
    	rm ${CTRL_PATH}
	;;
    *)
	echo "Usage $0 [start|stop]"
	exit 1
	;;

esac
