#!/bin/sh
[ -f /etc/bluedsl.conf ] && . /etc/bluedsl.conf
. /etc/autoconf.conf

case $1 in
    start)
		if [ ! "$ENABLE_PRINT_SERVER" = "1" ] ; then
			echo "Printserver not starting : \$ENABLE_PRINT_SERVER = $ENABLE_PRINT_SERVER"
			exit 0
		fi
		echo "Starting print_server"
		rm -f /var/run/printer0
		if [ ! -z "$CONFIG_LPRNG" ]; then
			rm -f /var/run/lpd.515
			rm -f /var/run/lprng
			mkdir -p -m 777 /var/spool/samba
			chmod -R a+rw /var/spool/samba
			/usr/bin/lpd &
		fi
		;;
    stop)    
		if [ ! -z "$CONFIG_LPRNG" ]; then
			echo "Killing lpd daemon"
			killall lpd
			rm -f -r /var/spool/samba/*
			rm -f /var/run/lpd.515
			rm -f /var/run/lprng
		fi
        rm -f /var/run/printer0
		;;
    status)
		if [ ! -z "$CONFIG_LPRNG" ]; then
			/usr/bin/lpc status
		fi
		;;
    *)
		echo "do nothing"
		;;
esac


