#!/bin/sh

VERBOSE=0

# dbg_echo messages are only printed when the VERBOSE flag is set.
dbg_echo() # (str)
{
	str=$1
	if [ $VERBOSE -eq 1 ]; then
		echo $str
	fi
}

case $1 in
	start)
		if [ -x /usr/bin/rssplugin ]; then
			echo " start rssplugin ..."
			/usr/bin/rssplugin -d
			echo " rssplugin is started."
		else
			dbg_echo " start rssplugin ..."
			dbg_echo " rssplugin not present."
		fi
		;;
	stop)
		killall rssplugin
		;;
	*)
		echo "Usage $0 [start|stop]"
		exit 1
		;;

esac

