#!/bin/sh
#. /etc_ro_fs/init.d/common
. /etc/autoconf.conf
. /etc/advancedservices.conf

mount_dir=$HDTOOLSDIR         

create_directories()
{
  if [ -e $mount_dir ]; then
		if ! [  -d $mount_dir/$MEDIADIR ]; then                        
				echo  Creating dir $mount_dir/$MEDIADIR            
				mkdir -p -m 777 $mount_dir/$MEDIADIR           
		fi
		
		if ! [ -d  $mount_dir/$SHAREDDIR ]; then                 
				echo Creating dir $mount_dir/$SHAREDDIR
				mkdir -p -m 777 $mount_dir/$SHAREDDIR                     
		fi
  fi
}

case $1 in
	start)
#		echo "samba: starting service ..."
		create_directories
		/usr/sbin/smbd -D 
		/usr/sbin/nmbd -D
		[ -f "/etc/init.d/btclient" ] && /etc/init.d/btclient start
		;;
	stop)
		[ -f "/etc/init.d/btclient" ] && /etc/init.d/btclient stop
		echo "samba: stopping service ..."
		killall smbd
		killall nmbd
		;;
	update)
#		echo "samba: updating service data ..."
		create_directories
		
		SD_STATUS=`ps -e|grep smbd|grep -v grep|wc -w`
		NMBD_STATUS=`ps -e|grep nmbd|grep -v grep|wc -w`
		
		# Fix for bug CPE_P00048847 - NMBD must be re-started because sending SIGHUP to reload smb.conf doesn't work reliably
		# smbd and nmbd shold be active, do not wait till smbd and nmbd are active (it will block CIFS clent message loop)
		# TODO: a CIFS client shold use a worker thread
		if [ "$SD_STATUS" -ne 0 ] && [ "$NMBD_STATUS" -ne 0 ]; then
			echo "samba: update - smbd and nmbd are running"
			killall -HUP smbd
			killall	nmbd
			
			TELLER=0
			NMBD_STATUS=`ps -e|grep nmbd|grep -v grep|wc -w`
		  while [ "$NMBD_STATUS" -ne 0 ]
      do
      	TELLER=`expr ${TELLER} + 1`
        sleep 1;
				NMBD_STATUS=`ps -e|grep nmbd|grep -v grep|wc -w`
				echo "samba: update - wait for nmbd to be stopped, status (${NMBD_STATUS}), iteration nb: (${TELLER})"
        if [ "$TELLER" -eq 3 ]; then
        	echo "samba: update - nmbd is NOT stopped in time !"
					break
				fi
      done

			/usr/sbin/nmbd -D
			TELLER=0
			NMBD_STATUS=`ps -e|grep nmbd|grep -v grep|wc -w`
		  while [ "$NMBD_STATUS" -eq 0 ]
      do
      	TELLER=`expr ${TELLER} + 1`
        sleep 1;
				NMBD_STATUS=`ps -e|grep nmbd|grep -v grep|wc -w`
				echo "samba: update - wait for nmbd to be started, status (${NMBD_STATUS}), iteration nb: (${TELLER})"
        if [ "$TELLER" -eq 3 ]; then
        	echo "samba: update - nmbd is NOT started in time !"
					break
				fi
      done
			
		else
			echo "samba: update - is failed either smbd or nmbd or both are not running"
		fi		
		;;
	
		#this will only restart the samba server if it was running before !!!!
	restart)
	
		echo "samba: restarting services ..."
		SD_STATUS=`ps -e|grep smbd|grep -v grep|wc -w`
		if [ "$SD_STATUS" -ne 0 ]; then
			echo "samba: restart - smbd IS running"
			killall smbd
		fi
		
		NMBD_STATUS=`ps -e|grep nmbd|grep -v grep|wc -w`
		if [ "$NMBD_STATUS" -ne 0 ]; then
			echo "samba: restart - nmbd IS running"
			killall nmbd
		fi
		sleep 2
		create_directories
		/usr/sbin/smbd -D
		/usr/sbin/nmbd -D
		;;
	prepare_fs)
		create_directories
		;;
	*)
		echo "samba: do nothing"
esac
