#!/bin/sh

ID_FILE='/var/run/transceiverd'
BIN_FILE='/usr/bin/transceiverd'
BIN_PATH=/usr/bin/transceiverd

case $1 in
    start)
	# start transceiverd 
	if [ -f "$BIN_FILE" ] ; then
    	    /bin/echo "transceiverd start ..."
            ${BIN_PATH} & 
	fi
	;;
    stop)
	# stop transceiverd
	if [ -f "$BIN_FILE" ] ; then
    	    /bin/echo "transceiverd stop ..."
	    if [ -f "$ID_FILE" ] ; then
    	        TRANSCEIVERD_ID=$(cat ${ID_FILE});
    	        /bin/echo ${TRANSCEIVERD_ID}
    	        kill ${TRANSCEIVERD_ID}
	        rm -f ${ID_FILE}
	    fi
	fi
	;;
    *)
	
esac


