#!/bin/sh

ID_FILE='/var/run/upnpavpl.pid'
BIN_FILE='/usr/bin/upnpavpl'

case $1 in
  start)
    /bin/echo "upnpavpl start ..."
    $BIN_FILE -d
    ;;
  stop)
    /bin/echo "upnpavpl stop ..."
    if [ -f "$ID_FILE" ] ; then
      CUSTOMAPD_ID=$(cat ${ID_FILE})
      kill ${CUSTOMAPD_ID}
      rm -f ${ID_FILE}
    fi
    ;;
  *)
esac
