#!/bin/sh

#echo HSO action=$ACTION devnum=$DEVNUM pid=$PRODUCT vid=$VENDOR

VRTDEV=veth1
MOBDEV=hso0
CONFF=/var/tmp/mobile.conf

case $ACTION in
    add)
	cat /proc/net/dev | grep $VRTDEV 1> /dev/null
	ERROR=$?
	if [ $ERROR != 0 ];
	then
		echo "[HSO script] virtual ethernet '$VRTDEV' device doesn't exist"
		exit $ERROR
	fi

	cat /proc/net/dev | grep $MOBDEV 1> /dev/null
	ERROR=$?
	if [ $ERROR != 0 ];
	then
		echo "[HSO script] mobile '$MOBDEV' device doesn't exist"
		exit $ERROR
	fi

	#insmod /lib/modules/2.6.8.1/kernel/net/bridge/bridge.ko
	modprobe bridge

	#echo CREATE BRIDGE
	brctl addbr hsobr

	#echo $? IFUP MOBDEV
	ifconfig $MOBDEV up
	#echo $? IFUP VRTDEV
	ifconfig $VRTDEV up

	#echo $? ADD MOBDEV
	brctl addif hsobr $MOBDEV

	# sequence important: ifconfig $VRTDEV up MUST become before *addif*
	#echo $? ADD VRTDEV
	brctl addif hsobr $VRTDEV

	#echo $? IFUP HSOBR
	ifconfig hsobr up
	
	#Write config file
	echo "VENDOR=$VENDOR
PRODUCT=$PRODUCT
ATPORT=/dev/ttyHS0
AT2PORT=/dev/ttyHS1" > $CONFF

	touch /var/run/hso.script
	;;
	
    remove)
	if [ -e /var/run/hso.script ];
	then
		rm -f $CONFF
		ifconfig hsobr down
		brctl delif hsobr $MOBDEV
		brctl delif hsobr $VRTDEV
		ifconfig $MOBDEV down
		ifconfig $VRTDEV down
		brctl delbr hsobr
		rmmod bridge

		rm -f /var/run/hso.script
	fi
	;;
esac

exit 0
                    
