#!/bin/sh
#
# network setup script
#	Copyright (c) by Shuu Yamaguchi <shuu@wondernetworkresources.com>
#	Can be freely distributed and used under the terms of the GNU GPL.
#
# network
#

usbDevNumber=0
ledctrl="/usr/bin/ledctrl"

if [ -f /tmp/usbDevCount.file ] ;then
    usbDevNumber=`cat /tmp/usbDevCount.file`
else
    mktemp /tmp/usbDevCount.file
    echo -2 > /tmp/usbDevCount.file
    usbDevNumber=-2
fi

case $ACTION in
        add)
                usbDevNumber=`expr $usbDevNumber + 1`
                if test -f ${ledctrl} 
                then
                      if [ $usbDevNumber -gt 0 ]
              then
                $ledctrl cmd = ledup led_name = USBHOST
                fi
                fi
                ;;
        remove)
                usbDevNumber=`expr $usbDevNumber - 1`
                if [ $usbDevNumber -eq 0 ]
                then
                if test -f ${ledctrl}
                then
                $ledctrl cmd = leddown led_name = USBHOST
                fi
                fi
                ;;
esac

if [ $usbDevNumber -le -2 ];then
    usbDevNumber=-2
fi
echo $usbDevNumber > /tmp/usbDevCount.file    

