#!/bin/sh

#FWPATH=/archive/__BUILDNAME__/firmware
#Firmware location depends on build or custo name
#TRSV_DFLT=/archive/archive_xutw/active/trsv.def
#trsv.dflt location depends on build

if [ "$SUBSYSTEM" = "firmware" ]; then

 if [ "$ACTION" = "add" ] ; then
   echo "firmare upgrade : $DEVPATH : $FIRMWARE" 
   FWPATH=$(find /archive -name firmware -type d)
   echo 1 > /sys/$DEVPATH/loading
   if [ "$FIRMWARE" = "trsv" ]; then
     TRSV_DFLT=$(find /archive -name trsv.dflt -type f)
     if [ -f ${TRSV_DFLT} ]; then
       cat ${TRSV_DFLT} > /sys/$DEVPATH/data
     fi
   fi
   if [ "$FIRMWARE" = "phy" ]; then
      cat /userfs/config-bank-lastboot/dl/phy.conf > /sys/$DEVPATH/data
   fi
   if [ -f ${FWPATH}/${FIRMWARE}.gz ]; then
     gunzip -c ${FWPATH}/${FIRMWARE}.gz > /sys/$DEVPATH/data
   elif [ -f ${FWPATH}/${FIRMWARE} ]; then
     cat ${FWPATH}/${FIRMWARE} > /sys/$DEVPATH/data
   else
     cat /nmon/firmware/$FIRMWARE > /sys/$DEVPATH/data
   fi
   echo 0 > /sys/$DEVPATH/loading
 fi

fi
