#!/bin/sh

start () {
        cat /proc/cmdline | grep dofactoryreset > /dev/null
        FACTORYRESET=$?
        if [ $FACTORYRESET -eq 0 ]; then
                echo "Do factory reset - remove user.ini"
                rm -f /rw/dl/user.ini
                rm -f /rw/dl/linux.ip
                rm -f /rw/dl/nmonip
                rm -f /rw/dl/nmonmask
                rm -f /rw/dl/nmonsubnet
        fi
}


case $1 in
start)
        start
        ;;                                                                                                                                                   
stop)
        ;;
restart)
        ;;
*)
        echo "Usage $0 [start|stop|restart]"
        exit 1
        ;;
esac

