#!/bin/sh

case "$1" in
  start) # write 512 bytes of entropy-rich data to linux rng
	echo "Initializing random number generator"
	dd if=/dev/randseed of=/dev/urandom count=256 bs=2 2>/dev/null
	;;
  stop) # do not do anything
        :
	;;
  restart|reload)
	# do not do anything
	:
	;;
  *)
	echo "Usage: initrandom {start|stop|restart|reload}"
	exit 1
esac

exit 0

