#!/bin/sh

ID_FILE='/var/run/ledstatus.pid'
BIN_FILE='/usr/bin/ledstatus'

case $1 in
    start)
	if [ -f "$BIN_FILE" ] ; then
		/bin/echo "ledstatus start ..."
		/usr/bin/ledstatus -d
	fi
	;;
    stop)
	if [ -f "$BIN_FILE" ] ; then
		/bin/echo "ledstatus stop ..."
		if [ -f "$ID_FILE" ] ; then
			LEDSTATUS_ID=$(cat ${ID_FILE})
			/bin/echo ${LEDSTATUS_ID}
			kill ${LEDSTATUS_ID}
			rm -f ${ID_FILE}
		fi
	fi
	;;
    *)
	
esac

