#!/bin/sh

VERBOSE=0

# dbg_echo messages are only printed when the VERBOSE flag is set.
dbg_echo() # (str)
{
	str=$1
	if [ $VERBOSE -eq 1 ]; then
		echo $str
	fi
}

case $1 in
	start)
		if [ -x /usr/bin/longops ]; then
			echo " start longops ..."
			/usr/bin/longops -d
			echo " longops is started."
		else
			dbg_echo " start longops ..."
			dbg_echo " longops not present."
		fi
		;;
	stop)
		killall longops
		;;
	*)
		echo "Usage $0 [start|stop]"
		exit 1
		;;

esac

