#!/bin/sh

ID_FILE='/var/run/monitoripd.pid'
BIN_FILE='/usr/bin/monitoripd'

case $1 in
    start)
	# start monitoripd
	if [ -f "$BIN_FILE" ] ; then
		/bin/echo "monitoripd start ..."
		/usr/bin/monitoripd -d 
	fi
	;;

    stop)
	# stop monitoripd
	if [ -f "$BIN_FILE" ] ; then
		/bin/echo "monitoripd stop ..."
		if [ -f "$ID_FILE" ] ; then
			MONITORIPD_ID=$(cat ${ID_FILE})
			/bin/echo ${MONITORIPD_ID}
			kill ${MONITORIPD_ID}
			rm -f ${ID_FILE}
		fi
	fi
	;;
    *)
	
esac



