#!/bin/sh

VERBOSE=0
STDOUT_REDIRECT=/dev/null
STDERR_REDIRECT=/dev/nmon/nmontrace

if [ ! -w "$STDOUT_REDIRECT" ] ; then
        STDOUT_REDIRECT=/dev/null
fi
if [ ! -w "$STDERR_REDIRECT" ] ; then
        STDERR_REDIRECT=/dev/null
fi


# dbg_echo messages are only printed when the VERBOSE flag is set.
dbg_echo() # (str)
{
	str=$1
	if [ $VERBOSE -eq 1 ]; then
		echo $str
	fi
}

case $1 in
	start)
		if [ -x /usr/bin/mud ]; then
                        # Start- CPE_P00095532  
			echo " mud ..."
			if [ -f /var/mud_flag.log ]; then
                            echo " mud start ..."
                            /usr/bin/mud -d -t /usr/share/file_type.ini > "$STDOUT_REDIRECT" 2> "$STDERR_REDIRECT"
			fi
			# End- CPE_P00095532 		
		else
                         # Start- CPE_P00095532   
			dbg_echo " mud(dbg) ..."
			dbg_echo " mud not present (dbg)."
                        # End- CPE_P00095532  
		fi
		;;
	stop)
                # CPE_P00095532 
		echo "stop mud ..."
		killall mud
		;;
                 # Start- CPE_P00095532   
	restart)
		if [ -x /usr/bin/mud ]; then
			echo " restart mud ..."
                        /usr/bin/mud -d -t /usr/share/file_type.ini > "$STDOUT_REDIRECT" 2> "$STDERR_REDIRECT"
		else
			dbg_echo " restart mud(dbg) ..."
			dbg_echo " mud not present (dbg)."
		fi
		;;
                 # End - CPE_P00095532   
	*)
		echo "Usage $0 [start|stop]"
		exit 1
		;;

esac
