#!/bin/sh

# make everything to work relatively
# so we have a fake "ROOT"
# this script is located in ROOT/etc/init.d
# thus root is ROOT/etc/init.d/../..
#MYSCRIPTDIR=$(dirname $(pwd)/$0)
case $0 in
/*)
        # absolute path
        MYSCRIPTDIR="$(dirname ${0})"
        ;;
*)
        # relative path
        MYSCRIPTDIR="$(dirname $(pwd)/${0})"
        ;;
esac

MYROOT="${MYSCRIPTDIR}/../.."

MVFS_USER="mvfs"
MVFS_UID=499
MVFS_GROUP="daemon"
MVFS_MOUNT_DIR="/var/mvfs"


mvfs_adduser()
{
  MVFS_GID=`cat /etc/group | grep ${MVFS_GROUP} | cut -d : -f 3`
  if [ -z "$MVFS_GID" ]
  then
    addgroup "$MVFS_GROUP"
    MVFS_GID=`cat /etc/group | grep ${MVFS_GROUP} | cut -d : -f 3`
    if [ -z "$MVFS_GID" ]
    then
      MVFS_GID=0
    fi
  fi
  if [ "`id -un ${MVFS_USER} 2>/dev/null`" != "${MVFS_USER}" ]
  then
    echo "${MVFS_USER}:*:${MVFS_UID}:${MVFS_GID}::${MVFS_MOUNT_DIR}:/bin/sh" >> /etc/passwd
  fi
}

case $1 in
    start)
	if ! test -f ${MYROOT}/var/run/vfspl.pid
	then
		# if vfspl is not running, don't even bother to attempt starting mvfspl
		exit -1
	fi
	if test -f ${MYROOT}/usr/bin/mvfspl
	then
		mvfs_adduser
		su -c "${MYROOT}/usr/bin/mvfspl -d" "${MVFS_USER}"
	fi
	;;
    stop)
	if test -f ${MYROOT}/var/run/mvfspl.pid
	then
		kill `cat ${MYROOT}/var/run/mvfspl.pid`
	fi
	;;
    *)
	echo "Usage $0 [start|stop]"
	exit 1
	;;

esac
