#!/bin/sh

. /etc/autoconf.conf

# Function to determine whether an interface exists (based on return code of ifconfig)
ifexists() { # Parameters: $1=interface
        ifconfig $1 >/dev/null 2>&1
        return $?
}

start () {
	if ifexists usb0; then
		ifconfig usb0 192.168.2.1
	fi
	ifconfig lo 127.0.0.1
	route add -net 127.0.0.0 netmask 255.0.0.0 lo
	hostname Linux

	ifconfig veth0 up
	#route add default gw $IP_NMON
}

stop () {
	ifconfig veth0 down
	ifconfig usb0 down
}


case $1 in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage $0 [start|stop|restart]"
		exit 1
		;;
esac

		
