#!/bin/sh

ID_FILE='/var/run/ploamd'
BIN_FILE='/usr/bin/ploamd'
BIN_PATH=/usr/bin/ploamd

case $1 in
    start)
	# start ploamd 
	if [ -f "$BIN_FILE" ] ; then
    	    /bin/echo "ploamd start ..."
            ${BIN_PATH} & 
	fi
	;;
    stop)
	# stop ploamd
	if [ -f "$BIN_FILE" ] ; then
    	    /bin/echo "ploamd stop ..."
	    if [ -f "$ID_FILE" ] ; then
    	        PLOAMD_ID=$(cat ${ID_FILE});
    	        /bin/echo ${PLOAMD_ID}
    	        kill ${PLOAMID_ID}
	        rm -f ${ID_FILE}
	    fi
	fi
	;;
    *)
	
esac


