#!/bin/sh

ID_FILE='/var/run/todd.pid'
BIN_FILE='/usr/bin/todd'

case $1 in
    start)
	# start todd
	if [ -f "$BIN_FILE" ] ; then
		/bin/echo "todd start ..."
		/usr/bin/todd -d
	fi
	;;
    stop)
	# stop todd
	if [ -f "$BIN_FILE" ] ; then
		/bin/echo "todd stop ..."
		if [ -f "$ID_FILE" ] ; then
			TODD_ID=$(cat ${ID_FILE})
			/bin/echo ${TODD_ID}
			kill ${TODD_ID}
			rm -f ${ID_FILE}
		fi
	fi
	;;
    *)
	
esac



